apiVersion: v1
kind: Secret
metadata:
  name: jkbank-secrets
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "root"
  MINIO_ROOT_PASSWORD: "supersecret"
  MINIO_ACCESS_KEY: "loki"
  MINIO_SECRET_KEY: "supersecret"
  KEYCLOAK_ADMIN: "superuser"
  KEYCLOAK_ADMIN_PASSWORD: "superuser"
  RABBITMQ_DEFAULT_USER: "guest"
  RABBITMQ_DEFAULT_PASS: "guest"