services:
  accounts:
    image: "jkdev1998/accounts:tag1"
    container_name: accounts-ms
    ports:
        - "9080:9080"
    deploy:
        resources:
          limits:
            memory: 700m
    networks:
      - jkbank
  loans:
    image: "jkdev1998/loans:tag1"
    container_name: loans-ms
    ports:
      - "10000:10000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - jkbank
  cards:
    image: "jkdev1998/cards:tag1"
    container_name: cards-ms
    ports:
      - "9090:9090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - jkbank
networks:
  jkbank:
    driver: "bridge"

