spring:
  application:
    name: "configserver"
  profiles:
#    active: native
    active: git
  cloud:
    config:
      server:
#        native:
#          search-locations: "classpath:/config"
        git:
          uri: "https://github.com/JayakrishnanJS/jkbank-config"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

encrypt:
  key: "s3cr3tK3yF0rJKb4nk"

server:
    port: 8071